###
POST http://localhost:9000/api/crear HTTP/1.1
Content-Type: application/json

{
    "usuarioNombre": "Kevin",
    "usuarioApellidos": "Codes",
    "usuarioImagenProfile": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Guido_van_Rossum_OSCON_2006.jpg/1200px-Guido_van_Rossum_OSCON_2006.jpg",
    "usuarioFechaBorn": "27-03-2002",
    "usuarioTel": "4641029384",
    "usuarioCorreo": "kevin_codes@xido.rutas",
    "usuarioContrasena": "putoelqueladesencripte"

}


###